version: '3.8'
services:
  db-business:
    image: postgres:13
    container_name: db-business
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mycar-business
    volumes:
      - postgres_data_business:/var/lib/postgresql/data
      - ./db-business/init:/docker-entrypoint-initdb.d

  db-notifications:
    image: postgres:13
    container_name: db-notifications
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mycar-notifications
    volumes:
      - postgres_data_notifications:/var/lib/postgresql/data
      - ./db-notifications/init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT


  business:
    build:
      context: ./business
    container_name: business
    ports:
      - "8081:8080"
    depends_on:
      - db-business
      - kafka
    environment:
      KAFKA_TOPIC_NAME: B2N-topic
      KAFKA_URL: kafka:9092
      SPRING_PROFILES_ACTIVE: local
      DATABASE_URL: jdbc:postgresql://db-business:5432/mycar-business
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      SQL_INIT_MODE: never

  notifications:
    build:
      context: ./notifications
    container_name: notifications
    ports:
      - "8082:8080"
    depends_on:
      - db-notifications
    environment:
      KAFKA_TOPIC_NAME: B2N-topic
      KAFKA_URL: kafka:9092
      SPRING_PROFILES_ACTIVE: local
      DATABASE_URL: jdbc:postgresql://db-notifications:5432/mycar-notifications
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      SQL_INIT_MODE: never

volumes:
  postgres_data_business:
  postgres_data_notifications: