name: Deploy to Server

on:
  push:
    branches:
      - feature/test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 164.90.162.202 >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa root@164.90.162.202 "
          cd /var/www/my-car &&
          docker-compose down &&
          docker-compose up -d --build
          "